"""Add location geometry to incident

Revision ID: b220857e9fea
Revises: 55a8ec12216c
Create Date: 2025-12-24 16:02:21.320833+00:00

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b220857e9fea'
down_revision = '55a8ec12216c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    # op.create_index('idx_incidents_location', 'incidents', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_incidents_location', table_name='incidents', postgresql_using='gist')
    op.drop_column('incidents', 'location')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
