"""Add incident routing schema

Revision ID: 55a8ec12216c
Revises: 001_initial
Create Date: 2025-12-24 15:59:36.601246+00:00

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55a8ec12216c'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_rewards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('reporter_id', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('confirmations_at_payout', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('driver_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_driver_ratings_driver_id', table_name='driver_ratings')
    op.drop_index('idx_driver_ratings_rating', table_name='driver_ratings')
    op.create_index(op.f('ix_driver_ratings_driver_id'), 'driver_ratings', ['driver_id'], unique=False)
    op.alter_column('drivers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_drivers_is_available', table_name='drivers')
    op.drop_index('idx_drivers_is_online', table_name='drivers')
    op.drop_index('idx_drivers_user_id', table_name='drivers')
    op.drop_index('idx_drivers_vehicle_type', table_name='drivers')
    op.drop_index('idx_drivers_verification_status', table_name='drivers')
    op.create_index(op.f('ix_drivers_is_available'), 'drivers', ['is_available'], unique=False)
    op.create_index(op.f('ix_drivers_is_online'), 'drivers', ['is_online'], unique=False)
    op.create_index(op.f('ix_drivers_vehicle_type'), 'drivers', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_drivers_verification_status'), 'drivers', ['verification_status'], unique=False)
    op.add_column('incidents', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('severity_score', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('verified_by', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('reward_status', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('affected_routes', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['verified_by'], ['id'])
    op.alter_column('passenger_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_passenger_ratings_passenger_id', table_name='passenger_ratings')
    op.create_index(op.f('ix_passenger_ratings_passenger_id'), 'passenger_ratings', ['passenger_id'], unique=False)
    op.alter_column('rides', 'requested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_rides_driver_id', table_name='rides')
    op.drop_index('idx_rides_passenger_id', table_name='rides')
    op.drop_index('idx_rides_payment_status', table_name='rides')
    op.drop_index('idx_rides_requested_at', table_name='rides')
    op.drop_index('idx_rides_status', table_name='rides')
    op.create_index(op.f('ix_rides_payment_status'), 'rides', ['payment_status'], unique=False)
    op.create_index(op.f('ix_rides_requested_at'), 'rides', ['requested_at'], unique=False)
    op.create_index(op.f('ix_rides_ride_type'), 'rides', ['ride_type'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_firebase_uid', table_name='users')
    op.drop_index('idx_users_phone_hash', table_name='users')
    op.drop_constraint('users_firebase_uid_key', 'users', type_='unique')
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.create_unique_constraint('users_firebase_uid_key', 'users', ['firebase_uid'])
    op.create_index('idx_users_phone_hash', 'users', ['phone_hash'], unique=False)
    op.create_index('idx_users_firebase_uid', 'users', ['firebase_uid'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_ride_type'), table_name='rides')
    op.drop_index(op.f('ix_rides_requested_at'), table_name='rides')
    op.drop_index(op.f('ix_rides_payment_status'), table_name='rides')
    op.create_index('idx_rides_status', 'rides', ['status'], unique=False)
    op.create_index('idx_rides_requested_at', 'rides', [sa.text('requested_at DESC')], unique=False)
    op.create_index('idx_rides_payment_status', 'rides', ['payment_status'], unique=False)
    op.create_index('idx_rides_passenger_id', 'rides', ['passenger_id'], unique=False)
    op.create_index('idx_rides_driver_id', 'rides', ['driver_id'], unique=False)
    op.alter_column('rides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rides', 'requested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_passenger_ratings_passenger_id'), table_name='passenger_ratings')
    op.create_index('idx_passenger_ratings_passenger_id', 'passenger_ratings', ['passenger_id'], unique=False)
    op.alter_column('passenger_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'updated_at')
    op.drop_column('incidents', 'status')
    op.drop_column('incidents', 'expires_at')
    op.drop_column('incidents', 'affected_routes')
    op.drop_column('incidents', 'reward_status')
    op.drop_column('incidents', 'verified_by')
    op.drop_column('incidents', 'verified_at')
    op.drop_column('incidents', 'is_verified')
    op.drop_column('incidents', 'severity_score')
    op.drop_column('incidents', 'downvotes')
    op.drop_column('incidents', 'upvotes')
    op.drop_index(op.f('ix_drivers_verification_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_vehicle_type'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_is_online'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_is_available'), table_name='drivers')
    op.create_index('idx_drivers_verification_status', 'drivers', ['verification_status'], unique=False)
    op.create_index('idx_drivers_vehicle_type', 'drivers', ['vehicle_type'], unique=False)
    op.create_index('idx_drivers_user_id', 'drivers', ['user_id'], unique=False)
    op.create_index('idx_drivers_is_online', 'drivers', ['is_online'], unique=False)
    op.create_index('idx_drivers_is_available', 'drivers', ['is_available'], unique=False)
    op.alter_column('drivers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_driver_ratings_driver_id'), table_name='driver_ratings')
    op.create_index('idx_driver_ratings_rating', 'driver_ratings', ['rating'], unique=False)
    op.create_index('idx_driver_ratings_driver_id', 'driver_ratings', ['driver_id'], unique=False)
    op.alter_column('driver_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('incident_rewards')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
